### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by erinyoung** [StaPH-B/staphb_toolkit#48]
Someone contacted me on twitter with an error when they went to run staph-wf

I'm putting this here

> Dr. Young, I tried to install staphb, but it kept giving me error like this. Could you advise what is wrong? Thanks. 
-JXXXXXX:
```
~/Downloads/staphb_toolkit$ staphb-wf
Traceback (most recent call last):
  File "/home/mdxhrd/Downloads/staphb_toolkit/staphb-wf", line 3, in <module>
    import staphb_toolkit.toolkit_workflows as tk_work
  File "/home/mdxhrd/Downloads/staphb_toolkit/staphb_toolkit/toolkit_workflows.py", line 11, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 15, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 218
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
```

They cloned the repository from github, and then I don't really know what happened. I haven't been able to replicate what happened. They use ubuntu. This might be a python2 vs python3 issue. 

When I figure it out and how to fix it, I'll update this issue with some suggestions on more information to put in the readme.

**Comment by erinyoung** [comment]
This can be closed. Turns out this is the error message that happens when you try to install with python2 instead of python3.
